### ISSUE TITLE
Error al levantar el proyecto localmente

### ISSUE THREAD

**Issue by almanuel** [concristina/escrutinio-ciudadano#2]
Estoy intentando levantar la app localmente. Surgió este error en el paso 5.  
Parece que hay alguún problema con la importacion de content types. 
Tienen idea que puede estar pasando? 

```bash
→ python manage.py loaddata fixtures/*
Traceback (most recent call last):
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
psycopg2.IntegrityError: insert or update on table "auth_permission" violates foreign key constraint "auth_permission_content_type_id_2f476e4b_fk_django_co"
DETAIL:  Key (content_type_id)=(19) is not present in table "django_content_type".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 115, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 243, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/manu/dev/escrutinio-ciudadano/escrutinio-ciudadano/lib/python3.6/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "auth_permission" violates foreign key constraint "auth_permission_content_type_id_2f476e4b_fk_django_co"
DETAIL:  Key (content_type_id)=(19) is not present in table "django_content_type".
```
Gracias

**Comment by mgaitan** [comment]
@manuelpira ahi exporté sólo el modelo `User` de `auth`, probá si sigue dando problemas por favor.

**Comment by almanuel** [comment]
Gracias @mgaitan, anduvo bien el `loaddata`. Al correr `runserver` no hay errores de consola, sin embargo hay un error en el browser. Borrando las lineas 2 y 10, levantó bien la app! :)
 
![error_google_analytics](https://user-images.githubusercontent.com/3343612/30245792-3b5e2106-95bb-11e7-8bfe-816a8d945925.png)

**Comment by mgaitan** [comment]
ok, defini esa constante en tu local_settings.py, con un valor como indica el error.

**Comment by almanuel** [comment]
Ah listo, perfecto!

Un detalle: varias veces mencionás `local_settings.py` pero en el repo solo hay un `settings.py`. Debería crear una copia de ese settings y llamarla así para tener mis settings locales? 

Soy nuevo en django, gracias por la paciencia!

**Comment by almanuel** [comment]
Ahí probé creando un `local_settings.py` y evidentemente funciona así. De hecho está en el `.gitignore`

Gracias @mgaitan !
